apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template: 
    metadata:
      labels:
        env: dev
        app: cache
    spec:
      containers:
      - name: cache
        image: redis:5-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: cache-db
            mountPath: /data
      volumes:
        - name: cache-db
          hostPath:
            path: /mnt/cache
