apiVersion: v1
kind: Service
metadata:
  name: messaging
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  namespace: __namespace__
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: messaging
  template: 
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - name: messaging
        image: nats-streaming:0.11.2
        args:
          - "-cid"
          - "datastack-cluster"
          - "--store"
          - "FILE"
          - "--dir"
          - "/store"
          - "--max_age"
          - "24h"
          - "--max_channels"
          - "0"
        ports:
          - containerPort: 4222
        volumeMounts:
          - name: messaging-store
            mountPath: /store
      volumes:
        - name: messaging-store
          hostPath:
            path: /mnt/store
